language: java

jdk:
  - openjdk15

sudo: false

env:
  global:
    - CODECOV_TOKEN="1b2aeb2e-89fa-4ed1-b8b2-2f964e34c0bd"

# после выполнения сборки запустить скрипт, который будет собирать статистику по JaCoCo
# Здесь используется сторонний сервис https://codecov.io/
after_success:
  - bash <(curl -s https://codecov.io/bash)

notifications:
  email:
    recipients:
      -ladykati73@gmail.com
    on_success: never # default: change
    on_failure: always # default: always